### PR TITLE
Getting current plan should require read permission, not write

### PR DESCRIPTION
**Pull request by Nicolaidavies**
Fixed an incorrect permission. 

Fixes bug experienced here: https://github.com/disarm-platform/user-requests-and-feedback/issues/93#issuecomment-408387015

Might be a good thing to check all permissions for all users before we go ahead and merge this in.

### CODE REVIEW

**Comment by Nicolaidavies** [comment]
@onlyjsmith Can you take a look at this?

**Comment by onlyjsmith** [comment]
@Nicolaidavies did you 'check all permissions for all users before we go ahead and merge this in.'? Or think we don't need to?

**Comment by Nicolaidavies** [comment]
@onlyjsmith I haven't checked it yet. I can do that now.

**Comment by Nicolaidavies** [comment]
I've checked and we are alright to merge this in.

**Pull request merged**
